name: coriander
description: A new Flutter application.

publish_to:

version: 1.0.0+1

environment:
  sdk:

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - Images/ハックフェス.jpg
    - Images/LAB3.jpg

